### ISSUE TITLE
无法签到啊

### ISSUE THREAD

**Issue by tzxiaozhen88** [wuzhi05/MyActions#4]
🔔京东资产变动通知, 开始!
您的cookie选择的是用&隔开

====================共有2个京东账号Cookie=========

==================脚本执行- 北京时间(UTC+8)：2021/10/16 下午12:22:07=====================

❗️京东资产变动通知, 错误!

********开始【京东账号1】88732844-31776020******

"connect ECONNREFUSED 106.39.166.88:443"
京东资产变动通知 API请求失败，请检查网路重试

❗️京东资产变动通知, 错误!
TypeError: Cannot read property 'body' of undefined
    at /jd/scripts/jd_bean_change.js:470:48
    at /jd/scripts/jd_bean_change.js:887:5763
    at processTicksAndRejections (internal/process/task_queues.js:95:5)

东东农场: API查询请求失败 ‼️‼️
"connect ECONNREFUSED 106.39.166.88:443"
function_id:taskInitForFarm

❗️京东资产变动通知, 错误!

东东农场: API查询请求失败 ‼️‼️
"connect ECONNREFUSED 106.39.166.88:443"

❗️京东资产变动通知, 错误!

"connect ECONNREFUSED 106.39.166.88:443"
京东资产变动通知 API请求失败，请检查网路重试
"connect ECONNREFUSED 106.39.170.211:443"
request_algo 签名参数API请求失败，请检查网路重试
"connect ECONNREFUSED 36.110.180.72:443"
API请求失败，请检查网路重试
请求失败
"connect ECONNREFUSED 106.39.166.88:443"
京东资产变动通知 API请求失败，请检查网路重试
未知情况：undefined
未知情况，跳出
"connect ECONNREFUSED 36.110.180.72:443"
京东资产变动通知 API请求失败，请检查网路重试
"connect ECONNREFUSED 36.110.180.72:443"
京东资产变动通知 API请求失败，请检查网路重试

东东萌宠: API查询请求失败 ‼️‼️
"connect ECONNREFUSED 106.39.166.88:443"

❗️京东资产变动通知, 错误!

东东萌宠: API查询请求失败 ‼️‼️
"connect ECONNREFUSED 106.39.166.88:443"

❗️京东资产变动通知, 错误!

❌ 京东资产变动通知, 失败! 原因: TypeError: Cannot read property 'code' of undefined!

🔔京东资产变动通知, 结束! 🕛 29.192 秒

**Comment by tzxiaozhen88** [comment]
是我自己的问题，更新了 portainer版本现在ok了
