### ISSUE TITLE
jd_get_share_code: jxcfd的shareCode接口已失效

### ISSUE THREAD

**Issue by kaifeiji** [wuzhi05/MyActions#9]
jxcfd获取shareCode时，以下接口会报错：

```
https://m.jingxi.com/jxcfd/user/QueryUserInfo?strZone=jxcfd&bizCode=jxcfd&source=jxcfd&dwEnv=7&_cfd_t=1634699857609&ptag=138631.26.55&undefined&_ste=1&_=1634699857609&sceneval=2&g_login_type=1&g_ty=ls
```

报错信息：

```
❗️获取互助码, 错误!
SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at /jd/scripts/jd_get_share_code.js:580:18
    at isSurge.isLoon.isQuanX.isNode.got.on.then.message (/jd/scripts/jd_get_share_code.js:737:4774)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

1、该问题并不影响其他游戏获取shareCode

2、从游戏界面和规则来看，目前（2021-10-20）雇佣导游已经不再需要好友助力，只需花费金币即可

3、参考JDHelloWorld的代码，貌似已经移除了jxcfd的shareCode

4、jd_get_share_code是否已经可以移除或注释jxcfd部分代码？

**Comment by wuzhi05** [comment]
好的 ，晚点回去搞一下
